@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package gigaherz.survivalist.state.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;