@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package gigaherz.common.state.implementation;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;