@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package gigaherz.survivalist.state.implementation;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;