@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package gigaherz.survivalist.api.state;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;