@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package gigaherz.survivalist.torchfire;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;