@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.survivalist.integration;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;