@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package gigaherz.survivalist.integration.analyzer;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;